"""initial schema

Revision ID: e96abe946326
Revises:
Create Date: 2026-07-22 18:55:03.229199

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e96abe946326"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("marketplace", postgresql.ENUM("wb", "ozon", name="marketplace"), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("marketplace", "sku", name="uq_products_marketplace_sku"),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("geo", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("mode", postgresql.ENUM("scheduled", "manual", name="run_mode"), nullable=False),
        sa.Column("status", postgresql.ENUM("running", "done", "failed", name="run_status"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "measure_queue",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "in_progress", "done", "failed", name="queue_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_measure_queue_status_run", "measure_queue", ["status", "run_id"], unique=False)
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_base", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("price_card", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_price_snapshots_product_region_captured",
        "price_snapshots",
        ["product_id", "region_id", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("queue_id", sa.BigInteger(), nullable=False),
        sa.Column("proxy_ref", sa.String(), nullable=True),
        sa.Column(
            "outcome",
            postgresql.ENUM("ok", "soft_ban", "hard_ban", "timeout", "error", name="outcome"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["measure_queue.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attempts")
    op.drop_index("ix_price_snapshots_product_region_captured", table_name="price_snapshots")
    op.drop_table("price_snapshots")
    op.drop_index("ix_measure_queue_status_run", table_name="measure_queue")
    op.drop_table("measure_queue")
    op.drop_table("runs")
    op.drop_table("regions")
    op.drop_table("products")
    # ### end Alembic commands ###
    postgresql.ENUM(name="outcome").drop(op.get_bind(), checkfirst=False)
    postgresql.ENUM(name="queue_status").drop(op.get_bind(), checkfirst=False)
    postgresql.ENUM(name="run_status").drop(op.get_bind(), checkfirst=False)
    postgresql.ENUM(name="run_mode").drop(op.get_bind(), checkfirst=False)
    postgresql.ENUM(name="marketplace").drop(op.get_bind(), checkfirst=False)
